- import_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: Debian.yml
  when: ansible_os_family == 'Debian' 

- name: Check Node.js Version
  shell: node -v
  register: node_ver
  notify: Node.js Version